LifecycleAPI.configs({
	"lifecycle-api":"/publisher/apis/lifecycles",
	"lifecycle-definition-api":"/apis/lifecycles",
	"svgContainer":"svg",
	"graphContainer":"g",
	"lifecycleRenderingArea":"lifecycle-rendering-area",
	"lifecycleActionArea":"lifecycle-actions",
	"lifecycleChecklistArea":"lifecycle-checklist",
	"lifecycleChecklistBlock":"lifecycle-checklist-overlay",
	"lifecycleActionOverlay":"lifecycle-actions-overlay",
	"lifecycleHistoryArea":"lifecycle-history",
	"lifecycleInformationArea":"lifecycle-information",
	"lifecycleCommentTextArea":"lifecycle-comment",
	"lifecycleTransitionUIArea":"lifecycle-transition-ui",
	"lifecycleNotificationsArea":"lifecycle-notifications",
	"lifecycleGlobalNotificationsArea":"lifecycle-global-notifications",
	"lifecycleTemplateNotficationError":"lifecycle-notification-error",
	"lifecycleTemplateNotificationInfo":"lifecycle-notification-info",
	"lifecycleTemplateNotificationWarn":"lifecycle-notification-warn",
	"lifecycleTemplateNotificationSuccess":"lifecycle-notification-success",
	"lifecycleTransitionInputsFieldsArea":"lifecycle-transition-inputs-fields-container",
	"lifecycleTransitionInputsActionsArea":"lifecycle-transition-inputs-actions-container",
	"lifecycleTRansitionInputsFieldsForm":"lifecycle-transition-inputs-field-form",
	"apiLCBase":"/apis/asset",
	"apiChangeState":"/change-state",
	"apiFetchState" :"/state",
	"apiUpdateChecklist":"/update-checklist",
	"apiFetchHistory":"/lifecycle-history",
	"msgCannotChangeState":"You do not have permission to change states",
	"msgStateChangedSuccess":"State updated successfully",
	"msgStateChangeError":"State could not be updated",
	"msgChecklistUpdateSuccess":"Checklist updated successfully",
	"msgChecklistUpdateError":"Checklist was not updated",
    "deleteActionArea":"Delete"
});