LifecycleAPI.configs({
	"lifecycle-api":"/publisher/apis/lifecycles",
	"lifecycle-definition-api":"/apis/lifecycles",
	"svgContainer":"svg",
	"graphContainer":"g",
	"lifecycleRenderingArea":"lifecycle-rendering-area",
	"lifecycleActionArea":"lifecycle-actions",
	"lifecycleChecklistArea":"lifecycle-checklist"
});