LifecycleAPI.configs({
	"lifecycle-api":"/publisher/apis/lifecycles",
	"lifecycle-definition-api":"/apis/lifecycles",
	"svgContainer":"svg",
	"graphContainer":"g",
	"lifecycleRenderingArea":"lifecycle-rendering-area",
	"lifecycleActionArea":"lifecycle-actions",
	"lifecycleChecklistArea":"lifecycle-checklist",
	"lifecycleChecklistBlock":"lifecycle-checklist-overlay",
	"lifecycleVoteArea":"lifecycle-vote",
	"lifecycleVoteBlock":"lifecycle-vote-overlay",
	"lifecycleActionOverlay":"lifecycle-actions-overlay",
	"lifecycleHistoryArea":"lifecycle-history",
	"lifecycleInformationArea":"lifecycle-information",
	"lifecycleCommentTextArea":"lifecycle-comment",
	"lifecycleCommentContainer":"lifecycle-comments",
	"lifecycleTransitionUIArea":"lifecycle-transition-ui",
	"lifecycleNotificationsArea":"lifecycle-notifications",
	"lifecycleGlobalNotificationsArea":"lifecycle-global-notifications",
	"lifecycleTemplateNotficationError":"lifecycle-notification-error",
	"lifecycleTemplateNotificationInfo":"lifecycle-notification-info",
	"lifecycleTemplateNotificationWarn":"lifecycle-notification-warn",
	"lifecycleTemplateNotificationSuccess":"lifecycle-notification-success",
	"lifecycleTransitionInputsFieldsArea":"lifecycle-transition-inputs-fields-container",
	"lifecycleTransitionInputsActionsArea":"lifecycle-transition-inputs-actions-container",
	"lifecycleTRansitionInputsFieldsForm":"lifecycle-transition-inputs-field-form",
	"lifecycleTransitionInputUI":"lifecycle-transition-inputs-form",
	"lifecycleTransitionInputUICancelBtn":"transition-inputs-cancel-btn",
	"apiLCBase":"/apis/asset",
	"apiChangeState":"/change-state",
	"apiFetchState" :"/state",
	"apiUpdateChecklist":"/update-checklist",
    "apiUpdateVote":"/update-vote",
	"apiFetchHistory":"/lifecycle-history",
	"msgCannotChangeState":"You do not have permission to change states",
	"msgNoTraversableStates":"No traversable states for the selected lifecycle",
	"msgStateChangedSuccess":"State updated successfully",
	"msgStateChangeError":"State could not be updated. Please contact your administrator.",
	"msgChecklistUpdateSuccess":"Checklist updated successfully",
	"msgChecklistUpdateError":"Checklist was not updated",
    "msgVoteUpdateError":"Vote was not updated",
  "deleteActionArea":"Delete",
  "serverWarningMessage":"lifecycle-server-warning",
	"msgDetachLcError":"Lifecycle could not be detached",
	"msgAttachLcError":"Lifecycle could not be attached"
});
